Ok1ez
Project-Sloth/ps-mdt pull request #142
Opened 2023-02-03 19:32 UTC by OK1ez

2023-02-06 15:42 UTC, OK1ez commented
![Skjermbilde_20230206_163916](https://user-images.githubusercontent.com/87883296/217016466-f5c8842b-26af-4d1f-b476-2d77018e59a7.png)

2023-02-06 19:28 UTC, MonkeyWhisper requested changes
Great job, please see change requested

2023-02-06 19:28 UTC, MonkeyWhisper commented on ui/app.js
> +        "Summary:\n\n[Insert Report Summary Here]";
Please re-add this, since we are merging into the main branch, we want to keep all original things and just leave the current edit

2023-02-08 16:48 UTC, MonkeyWhisper approved these changes
I tested this myself and everything seems to be working normal, any issues, please report it.

2023-02-08 16:48 UTC, merged